export default {
  ACCESS_TOKEN_STORE_KEY: '_NA_ACCESS_TOK',
  REFRESH_TOKEN_STORE_KEY: '_NA_REFRESH_TOK',
  DEVICE_ID_STORE_KEY: '_NA_DEVICE_ID',
  LAST_BACKGROUND_MODE_VALUE: '_NA_LAST_BACKGROUND_MODE_VALUE',
  LAST_THINKING_MODE_VALUE: '_NA_LAST_THINKING_MODE_VALUE',
};